module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'api-gateway',
        'svc-authz',
        'svc-shops',
        'svc-requests',
        'svc-preview',
        'svc-ia-diff',
        'svc-quality',
        'svc-billing',
        'svc-notify',
        'svc-admin',
        'worker-e2e',
        'lib-common',
        'lib-firestore',
        'lib-shopify',
        'lib-git',
        'lib-llm',
        'sdk-authz',
        'contracts',
        'infra',
        'ops',
        'ci',
        'docs',
        'deps',
      ],
    ],
  },
};
