/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user context */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/tenants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new tenant */
    post: operations['createTenant'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/tenants/{tenantId}/access': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /** Check if user has access to tenant */
    head: operations['checkTenantAccess'];
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/tenants/{tenantId}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user roles for a specific tenant */
    get: operations['getTenantRoles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description ULID in Crockford base32 encoding */
    Ulid: string;
    /** @enum {string} */
    Role: 'Owner' | 'Collaborator' | 'PlatformAdmin';
    TenantRole: {
      tenantId: components['schemas']['Ulid'];
      roles: components['schemas']['Role'][];
    };
    UserContext: {
      uid: string;
      /** Format: email */
      email: string;
      tenants: components['schemas']['TenantRole'][];
    };
    ErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
  };
  responses: {
    /** @description Authentication required */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Insufficient permissions */
    ForbiddenError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Resource not found */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Resource conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Invalid request */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    /** @description Request ID for tracing (ULID format recommended) */
    XRequestId: string;
    /** @description Idempotency key for safe retries */
    XIdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            ok: boolean;
            /** @enum {string} */
            service: 'svc-authz';
            version: string;
          };
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: {
        /** @description Request ID for tracing (ULID format recommended) */
        'x-request-id'?: components['parameters']['XRequestId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User context retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserContext'];
        };
      };
      401: components['responses']['UnauthorizedError'];
      403: components['responses']['ForbiddenError'];
    };
  };
  createTenant: {
    parameters: {
      query?: never;
      header: {
        /** @description Request ID for tracing (ULID format recommended) */
        'x-request-id'?: components['parameters']['XRequestId'];
        /** @description Idempotency key for safe retries */
        'x-idempotency-key': components['parameters']['XIdempotencyKey'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Tenant created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tenantId: components['schemas']['Ulid'];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['UnauthorizedError'];
      409: components['responses']['ConflictError'];
    };
  };
  checkTenantAccess: {
    parameters: {
      query?: never;
      header?: {
        /** @description Request ID for tracing (ULID format recommended) */
        'x-request-id'?: components['parameters']['XRequestId'];
      };
      path: {
        tenantId: components['schemas']['Ulid'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User has access to tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components['responses']['ForbiddenError'];
      404: components['responses']['NotFoundError'];
    };
  };
  getTenantRoles: {
    parameters: {
      query?: never;
      header?: {
        /** @description Request ID for tracing (ULID format recommended) */
        'x-request-id'?: components['parameters']['XRequestId'];
      };
      path: {
        tenantId: components['schemas']['Ulid'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User roles retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tenantId: components['schemas']['Ulid'];
            roles: components['schemas']['Role'][];
          };
        };
      };
      403: components['responses']['ForbiddenError'];
      404: components['responses']['NotFoundError'];
    };
  };
}
